### ISSUE TITLE
some problem on setup.py

### ISSUE THREAD

**Issue by 123456789asdfjkl** [microsoft/SpareNet#26]
I run sh setup_env.sh,but meet some problems as following, env:Unbuntu 20.10, cuda 11.6
`(sparenet) changjunlin@changjunlin-System-Product-Name:~/下载/SpareNet-main$ sh setup_env.sh
[sudo] changjunlin 的密码： 
命中:1 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu impish InRelease
命中:2 http://cn.archive.ubuntu.com/ubuntu impish InRelease
获取:3 http://security.ubuntu.com/ubuntu impish-security InRelease [110 kB]
获取:4 http://cn.archive.ubuntu.com/ubuntu impish-updates InRelease [115 kB]
获取:5 http://cn.archive.ubuntu.com/ubuntu impish-backports InRelease [101 kB]
已下载 326 kB，耗时 2秒 (173 kB/s)
正在读取软件包列表... 完成
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
vim 已经是最新版 (2:8.2.2434-3ubuntu3.2)。
下列软件包是自动安装的并且现在不需要了：
  libatomic1:i386 libbsd0:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi8:i386 libgl1:i386 libgl1-mesa-dri:i386
  libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libicu67:i386 libllvm12:i386 libmd0:i386 libnvidia-compute-470:i386 libnvidia-decode-470:i386 libnvidia-encode-470:i386 libnvidia-fbc1-470:i386
  libpciaccess0:i386 libsensors5:i386 libstdc++6:i386 libvdpau1 libvulkan1:i386 libwayland-client0:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386
  libxcb-present0:i386 libxcb-randr0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcb-xfixes0:i386 libxcb1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxml2:i386 libxshmfence1:i386 libxxf86vm1:i386
  linux-headers-5.13.0-19 linux-headers-5.13.0-19-generic linux-image-5.13.0-19-generic linux-modules-5.13.0-19-generic linux-modules-extra-5.13.0-19-generic mesa-vdpau-drivers mesa-vulkan-drivers:i386
  screen-resolution-extra vdpau-driver-all
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 142 个软件包未被升级。
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成                 
tmux 已经是最新版 (3.1c-1build1)。
下列软件包是自动安装的并且现在不需要了：
  libatomic1:i386 libbsd0:i386 libdrm-amdgpu1:i386 libdrm-intel1:i386 libdrm-nouveau2:i386 libdrm-radeon1:i386 libdrm2:i386 libedit2:i386 libelf1:i386 libexpat1:i386 libffi8:i386 libgl1:i386 libgl1-mesa-dri:i386
  libglapi-mesa:i386 libglvnd0:i386 libglx-mesa0:i386 libglx0:i386 libicu67:i386 libllvm12:i386 libmd0:i386 libnvidia-compute-470:i386 libnvidia-decode-470:i386 libnvidia-encode-470:i386 libnvidia-fbc1-470:i386
  libpciaccess0:i386 libsensors5:i386 libstdc++6:i386 libvdpau1 libvulkan1:i386 libwayland-client0:i386 libx11-6:i386 libx11-xcb1:i386 libxau6:i386 libxcb-dri2-0:i386 libxcb-dri3-0:i386 libxcb-glx0:i386
  libxcb-present0:i386 libxcb-randr0:i386 libxcb-shm0:i386 libxcb-sync1:i386 libxcb-xfixes0:i386 libxcb1:i386 libxdmcp6:i386 libxext6:i386 libxfixes3:i386 libxml2:i386 libxshmfence1:i386 libxxf86vm1:i386
  linux-headers-5.13.0-19 linux-headers-5.13.0-19-generic linux-image-5.13.0-19-generic linux-modules-5.13.0-19-generic linux-modules-extra-5.13.0-19-generic mesa-vdpau-drivers mesa-vulkan-drivers:i386
  screen-resolution-extra vdpau-driver-all
使用'sudo apt autoremove'来卸载它(它们)。
升级了 0 个软件包，新安装了 0 个软件包，要卸载 0 个软件包，有 142 个软件包未被升级。
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.6'
running install
running bdist_egg
running egg_info
writing emd.egg-info/PKG-INFO
writing dependency_links to emd.egg-info/dependency_links.txt
writing top-level names to emd.egg-info/top_level.txt
/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'emd.egg-info/SOURCES.txt'
writing manifest file 'emd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.6'
running install
running bdist_egg
running egg_info
writing expansion_penalty.egg-info/PKG-INFO
writing dependency_links to expansion_penalty.egg-info/dependency_links.txt
writing top-level names to expansion_penalty.egg-info/top_level.txt
/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'expansion_penalty.egg-info/SOURCES.txt'
writing manifest file 'expansion_penalty.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 9, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.6'
running install
running bdist_egg
running egg_info
writing MDS.egg-info/PKG-INFO
writing dependency_links to MDS.egg-info/dependency_links.txt
writing top-level names to MDS.egg-info/top_level.txt
/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'MDS.egg-info/SOURCES.txt'
writing manifest file 'MDS.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 7, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.6'
running install
running bdist_egg
running egg_info
writing cubic_feature_sampling.egg-info/PKG-INFO
writing dependency_links to cubic_feature_sampling.egg-info/dependency_links.txt
writing top-level names to cubic_feature_sampling.egg-info/top_level.txt
/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'cubic_feature_sampling.egg-info/SOURCES.txt'
writing manifest file 'cubic_feature_sampling.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.6'
running install
running bdist_egg
running egg_info
writing gridding.egg-info/PKG-INFO
writing dependency_links to gridding.egg-info/dependency_links.txt
writing top-level names to gridding.egg-info/top_level.txt
/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'gridding.egg-info/SOURCES.txt'
writing manifest file 'gridding.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda-11.6'
running install
running bdist_egg
running egg_info
writing gridding_distance.egg-info/PKG-INFO
writing dependency_links to gridding_distance.egg-info/dependency_links.txt
writing top-level names to gridding_distance.egg-info/top_level.txt
/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py:381: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
  warnings.warn(msg.format('we could not find ninja.'))
reading manifest file 'gridding_distance.egg-info/SOURCES.txt'
writing manifest file 'gridding_distance.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
Traceback (most recent call last):
  File "setup.py", line 15, in <module>
    cmdclass={"build_ext": BuildExtension},
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_ext')
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 404, in build_extensions
    self._check_cuda_version()
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 777, in _check_cuda_version
    torch_cuda_version = packaging.version.parse(torch.version.cuda)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 56, in parse
    return Version(version)
  File "/home/changjunlin/anaconda3/envs/sparenet/lib/python3.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
`

**Comment by jiajia0408** [comment]
hi! I met the same problem. How can you solve it?
