### ISSUE TITLE
RuntimeError: CUDA error: out of memory

### ISSUE THREAD

**Issue by peng666** [microsoft/SpareNet#3]
I train the network through the following command：
`python train.py --gpu 0,,1 --workdir log --model msn`

When I execute the command, the program stops as follows：
> THCudaCheck FAIL file=/opt/conda/conda-bld/pytorch_1616554800319/work/aten/src/THC/THCCachingHostAllocator.cpp line=278 error=2 : out of memory
Traceback (most recent call last):
  File "train.py", line 83, in <module>
    main()
  File "train.py", line 79, in main
    model.runner()
  File "/home/pjw/projects5/SpareNet/runners/base_runner.py", line 338, in runner
    self.val()
  File "/home/pjw/projects5/SpareNet/runners/base_runner.py", line 209, in val
    self.val_step(items)
  File "/home/pjw/projects5/SpareNet/runners/msn_runner.py", line 54, in val_step
    _, (_, _, _, data) = items
  File "/home/pjw/projects5/SpareNet/utils/misc.py", line 18, in var_or_cuda
    x = x.cuda(non_blocking=True)
RuntimeError: CUDA error: out of memory

**Comment by peng666** [comment]
The problem has been solved, thank you
